// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddWidget: typeof import('./../src/components/AddWidget/index.vue')['default']
    CarouselBox: typeof import('./../src/components/containerBox/carouselBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeBox: typeof import('./../src/components/containerBox/sizeBox.vue')['default']
  }
}
