/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddWidget: typeof import('./../src/components/AddWidget/index.vue')['default']
    CarouselBox: typeof import('./../src/components/containerBox/carouselBox.vue')['default']
    ContainerBox: typeof import('./../src/components/ContainerBox/index.vue')['default']
    CustomIcon: typeof import('./../src/components/AddWidget/components/CustomIcon.vue')['default']
    Dialog: typeof import('./../src/components/Dialog/src/Dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeBox: typeof import('./../src/components/ContainerBox/SizeBox.vue')['default']
    UrlNavigation: typeof import('./../src/components/AddWidget/components/UrlNavigation.vue')['default']
    Widget: typeof import('./../src/components/AddWidget/components/Widget.vue')['default']
    Widgets: typeof import('../src/components/AddWidget/components/Widget.vue')['default']
  }
}
